export default {
  LOGO: require("../assets/image/Company-logo.svg"),
  WATCH: require("../assets/image/slider-image/Watch.jpg"),
  FARM: require("../assets/image/slider-image/Farm.jpg"),
  PARKING: require("../assets/image/slider-image/CarParking.jpg"),
  AMD: require("../assets/image/contact-us-icon/AMD.svg"),
  BROAN: require("../assets/image/contact-us-icon/Broan.svg"),
  GE: require("../assets/image/contact-us-icon/GE.svg"),
  HUAWEI: require("../assets/image/contact-us-icon/Huawei.svg"),
  PEPSICO: require("../assets/image/contact-us-icon/PepsiCo.svg"),
  FRIEDRICH: require("../assets/image/contact-us-icon/Friedrich.svg"),
  MEETING: require("../assets/image/confrens.jpg"),
  CARPARK: require("../assets/image/parkCar.jpg"),
  USER1: require("../assets/image/user1.jpg"),
  USER2: require("../assets/image/user2.jpg"),
  USER3: require("../assets/image/user3.jpg"),
  UNDERSTAND: require("../assets/image/feture-icon/Understand.svg"),
  EXPLORE: require("../assets/image/feture-icon/Explore.svg"),
  EXITUE: require("../assets/image/feture-icon/Execute.svg"),
  MANWORKING: require("../assets/image/manWorking.jpg"),
  CODING: require("../assets/image/Industry-icon/coding.svg"),
  CONSUMER: require("../assets/image/Industry-icon/Consumer.svg"),
  HEXANDON: require("../assets/image/Industry-icon/hexandon.svg"),
  MEDIC: require("../assets/image/Industry-icon/medic.svg"),
};
